### PR TITLE
Use environment cflags

### PR DESCRIPTION
**Pull request by withinboredom**
## What does this PR do?

An alternate implementation for #377 that takes the environment's CFLAGS.

## Checklist before merging

> If your PR involves the changes mentioned below and completed the action, please tick the corresponding option.
> If a modification is not involved, please skip it directly.

- [ ] If it's a extension or dependency update, make sure adding related extensions in `src/global/test-extensions.php`.
- [ ] If you changed the behavior of static-php-cli, add docs in [static-php/static-php-cli-docs](https://github.com/static-php/static-php-cli-docs) .
- [ ] If you updated `config/xxxx.json` content, run `bin/spc dev:sort-config xxx`.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
LGTM (I initially crafted a similar patch), but could you also update the macOS and the FreeBSD builder?

**Comment by dunglas** [comment]
Also, it could be useful and relatively easy to implement to support `{$LIBRARY_NAME}_CFLAGS` to allow setting flags for a specific library. This would enable adding debug symbols only to some libraries or to use different optimization levels depending on the library.

**Comment by withinboredom** [comment]
@dunglas Yep, almost got a patch done, just testing it now. I need to get to bed soon, but will finish it up tomorrow.

you can do `icu_CFLAGS="-O3"` to set just icu flags, or `CFLAGS="-O3"` to set all of them.

**Comment by withinboredom** [comment]
closing this PR though, as it isn't a truly viable approach (you can see progress on my fork's main branch).

**Comment by withinboredom** [comment]
@dunglas, I'm not going to continue with this as my investigation is complete and being able to optimize the libraries (even going so far as using `-flto`) doesn't seem to have much impact. It turns out the issue I'm hunting for may be related to libc implementations.

**Comment by dunglas** [comment]
Ok, do you have some draft to share that I can use as as base?
@crazywhalecc are you interested in a patch adding this feature?

**Comment by crazywhalecc** [comment]
> are you interested in a patch adding this feature?

@dunglas Does the feature you mentioned allow custom compilation commands and vars or switch glibc? 

The former may require opening a proposal, as it may involve significant code modifications. The latter can be achieved by using an environment detection tool and adding specific commands.

**Comment by dunglas** [comment]
@crazywhalecc my proposal was "just" to allow passing custom `CGLAGS` by setting `CGLAGS` (global) or `${LIBRARY_NAME}_CFLAGS` (specific lib) env vars.

**Comment by crazywhalecc** [comment]
@dunglas I created an issue to discuss the modifications to this mode.

**Pull request closed without merging**
