### PR TITLE
添加webui

### PR DESCRIPTION
**Pull request by jingjingxyk**
image

### CODE REVIEW

**Comment by jingjingxyk** [comment]
这部分代码抽取源于这里： https://github.com/swoole/swoole-cli/pull/165/files  。 并做了相应改动

image

**Comment by crazywhalecc** [comment]
webui 应该属于第三方组件，而不应该成为项目的一部分，这一点我是明确不同意合并在一起的。项目重点在于 cli，增加了 webui 徒增维护困难度，而且不统一，而且需要维护服务端。

**Comment by jingjingxyk** [comment]
@crazywhalecc  放这里了哈 https://static-php-cli-ui.jingjingxyk.com/

**Comment by crazywhalecc** [comment]
已和文档使用 Vue 编写整合：https://static-php-cli.zhamao.me/zh/guide/cli-generator.html

**Comment by takielias** [comment]
> @crazywhalecc 放这里了哈 https://static-php-cli-ui.jingjingxyk.com/
> 
> 依赖本项目的的这个文件： [ext.json](https://github.com/crazywhalecc/static-php-cli/blob/refactor/config/ext.json)

Does it support windows?

**Comment by crazywhalecc** [comment]
> Does it support windows?

@takielias 

The project does not currently support Windows, because Windows is a new underlying architecture, not Unix. This project started on Linux, and the refactored version supports macOS.

Windows support mainly has the following issues:

1. The compilation process of Windows is different from that of *nix, and the tool chain used is also different. Compiling each dependent library may encounter completely different problems.
2. PHP officially provides an independent installation package of the Windows version. Although it is not statically linked, you can easily package the entire PHP and dependent libraries in one folder, so Windows support is not a core requirement.
3. Windows supports WSL(2) environment. For developers, we recommend you to use WSL to develop PHP-related programs.
4. The demand for the Windows version will also be advanced according to the needs of all people who use this project. If there are many people who need it, I will support it as soon as possible.

**Comment by takielias** [comment]
@crazywhalecc 

As you rightly pointed out, there are significant challenges involved in adapting the project to Windows, from the different compilation process to the unique tool chain. However, it is worth mentioning that Windows remains a popular operating system among many developers, and I believe extending support to this platform would greatly increase the reach and applicability of your tool.

Given the potential benefits, I kindly request that you consider prioritizing the development of a Windows-compatible version. I understand that this is a significant task, and that the decision depends on the needs of all those using the project. I believe there are many others in the community who would benefit from such an addition and would support the endeavor.

Thank you for all the work you do for the community.

**Pull request closed without merging**
