### PR TITLE
fix pthreads4w URL

### PR DESCRIPTION
**Pull request by dunglas**
The current URL is down.

### CODE REVIEW

**Review by crazywhalecc — APPROVED** [review]

**Comment by crazywhalecc** [comment]
Oh, it seems pthreads4w is redundant, we could just remove it now.

**Comment by dunglas** [comment]
From `source.json` or also from `lib.json`?

**Comment by crazywhalecc** [comment]
Yeah. I just removed it :)

**Comment by crazywhalecc** [comment]
And now we have `download --for-extensions=xxx,yyy` options. If your workflow doesn't have caching, or if you don't need many extensions, you can reduce download time by only downloading the content related to the extensions. (By default, all sources of the specified extensions are included.)

**Pull request merged**
